### ISSUE TITLE
gradle版本升到4.0.2呗

### ISSUE THREAD

**Issue by ljackChen001** [KunMinX/Jetpack-MVVM-Scaffold#1]
本地在线依赖的话会报   Cause: org/gradle/api/internal/java/usagecontext/LazyConfigurationUsageContext

**Comment by KunMinX** [comment]
@ljackChen001 

bintray 对 gradle 4 以上支持不好，考虑到上传依赖库的需要，暂不升级

如有需要，可自行在本地升级

**Comment by ljackChen001** [comment]
刚刚更新了下  DataRepository没提交哇

**Comment by KunMinX** [comment]
@ljackChen001 
大概是缓存问题。编辑器 invalidate cache，或是重新拉一个新的项目即可
