### ISSUE TITLE
编译失败，代码缺失

### ISSUE THREAD

**Issue by aboutZZ** [KunMinX/Jetpack-MVVM-Scaffold#10]
- 在`com.kunminx.puremusic.player.PlayerManager`类，未实现`IPlayController`的以下方法：`getChangeMusicEvent`、`getPlayingMusicEvent`、`getPauseEvent`、`getPlayModeEvent`
- 在`PlayerManager`中的`mController`没有定义以下方法`getChangeMusicResult`、`getPlayingMusicResult`、`getPauseResult`、`getPlayModeResult`

![截图.png](https://s2.loli.net/2022/06/15/uvf46b1WZr5ejGR.png)

**Comment by KunMinX** [comment]
已修复。依赖升级至如下版本即可 

implementation "com.kunminx.player:player:3.5.0"

或 pull 最新源码。
