### ISSUE TITLE
DataBindingFragment 的 LifecycleOwner 问题

### ISSUE THREAD

**Issue by yishengma** [KunMinX/Jetpack-MVVM-Scaffold#7]
![image](https://user-images.githubusercontent.com/30148156/131651155-2b8ca3e5-6887-481d-9a4b-cfc6e0fbfd28.png)
Android 官方建议用 viewLifecycleOwner 替代 Fragment 的 LifecycleOwner 来避免内存泄露，这里使用 Fragment 是有什么考虑吗？
![image](https://user-images.githubusercontent.com/30148156/131651498-7734bd26-436e-47d2-b181-e43537fed281.png)

**Comment by KunMinX** [comment]
感谢你的反馈，已在 v4.0.0 版提交修正
